<?php
$labels['machinetranslated'] = 'Machine Translated using Qwen 3 30B A3B Instruct 2507. In case of errors please open an issue at <a href="https://github.com/bennet0496/kolab_2fa_webauthn">bennet0496/kolab_2fa_webauthn</a>';

$labels['factor'] = 'Facteur';
$labels['secret'] = 'Clé secrète';
$labels['created'] = 'Créé';
$labels['remove'] = 'Supprimer';
$labels['continue'] = 'Continuer';

$labels['2faloginfailed'] = 'Échec de la vérification du deuxième facteur';
$labels['choose_other'] = 'Choisir une autre méthode';

$labels['settingslist'] = 'Authentification à deux facteurs';
$labels['settingstitle'] = 'Facteurs d\'authentification';

$labels['totp'] = 'Application mobile (TOTP)';
$labels['hotp'] = 'Application mobile (HOTP)';
$labels['yubikey'] = 'YubiKey';
$labels['webauthn'] = 'Clé de sécurité';
$labels['backupcodes'] = 'Codes de secours';

$labels['or'] = 'ou';
$labels['yes'] = 'oui';
$labels['no'] = 'non';
$labels['again'] = 'essayer à nouveau';

$labels['label'] = 'Nom';
$labels['qrcode'] = 'Code QR';
$labels['showqrcode'] = 'Afficher le code QR';
$labels['qrcodeexplaintotp'] = 'Scannez le code QR ci-dessous avec votre application d\'authentification';
$labels['qrcodeexplainhotp'] = 'Scannez le code QR ci-dessous avec votre application d\'authentification';

$labels['yubikeyid'] = 'Votre ID YubiKey';
$labels['yubikeyidexplainyubikey'] = 'Appuyez une fois sur votre YubiKey et soumettez le code généré';

$labels["invalidauthenticatorresponse"] = "Réponse d'assertion d'authentificateur non valide";
$labels["invaliddatainup"] = "Données non valides dans le profil utilisateur.";
$labels["invalidsessiondata"] = "Données de session non valides.";
$labels["invalidauthenticatordata"] = "Données d'authentificateur non valides";


$labels['factorforcedinfo'] = "Vous devez configurer l'authentification à deux facteurs pour continuer, en ajoutant un facteur d'authentification ci-dessous.";
$labels['addfactor'] = 'Ajouter un facteur d\'authentification';
$labels['testfactor'] = 'Tester ce facteur';
$labels['verifycode'] = 'Vérifier le code';
$labels['verifycodeexplaintotp'] = 'Une fois que vous avez scanné le code QR, entrez le code à 6 chiffres généré par l\'application d\'authentification.';
$labels['verifycodeexplainhotp'] = 'Une fois que vous avez scanné le code QR, entrez le code à 6 chiffres généré par l\'application d\'authentification.';

$labels['onlysinglebackupcodes'] = 'Vous ne pouvez avoir qu\'un seul ensemble de codes de secours à la fois';

$labels['loginexpired'] = 'La demande de connexion a expiré ! Veuillez réessayer.';
$labels['authremoveconfirm'] = 'Voulez-vous vraiment supprimer ce facteur d\'authentification de votre compte ?';
$labels['verifycodemissing'] = 'Veuillez saisir le code de vérification provenant de votre appareil';

$labels['factorsavesuccess'] = 'Facteur d\'authentification enregistré avec succès';
$labels['factorremovesuccess'] = 'Facteur d\'authentification supprimé avec succès';
$labels['factorsaveerror'] = 'Échec de l\'enregistrement des paramètres du facteur d\'authentification';
$labels['codeverificationpassed'] = 'Vérification du code pour $method réussie';
$labels['codeverificationfailed'] = 'Échec de la vérification du code pour $method';

$labels['highsecurityrequired'] = 'Vérification supplémentaire requise';
$labels['highsecuritydialog'] = 'Pour protéger votre compte contre les menaces de sécurité, comme le vol de session ou une manipulation de vos données pendant votre absence, vous devez confirmer vos identifiants à l\'aide du facteur d\'authentification supplémentaire :';
$labels['enterhighsecurity'] = 'Confirmer';

