<?php
$labels['machinetranslated'] = 'Machine Translated using Qwen 3 30B A3B Instruct 2507. In case of errors please open an issue at <a href="https://github.com/bennet0496/kolab_2fa_webauthn">bennet0496/kolab_2fa_webauthn</a>';

$labels['factor'] = 'Tényező';
$labels['secret'] = 'Titkos kulcs';
$labels['created'] = 'Létrehozva';
$labels['remove'] = 'Eltávolítás';
$labels['continue'] = 'Folytatás';

$labels['2faloginfailed'] = 'A második tényező ellenőrzése sikertelen';
$labels['choose_other'] = 'Válassz másik módszert';

$labels['settingslist'] = 'Többtényezős hitelesítés';
$labels['settingstitle'] = 'Hitelesítési tényezők';

$labels['totp'] = 'Mobilalkalmazás (TOTP)';
$labels['hotp'] = 'Mobilalkalmazás (HOTP)';
$labels['yubikey'] = 'YubiKey';
$labels['webauthn'] = 'Biztonsági kulcs';
$labels['backupcodes'] = 'Helyreállítási kódok';

$labels['or'] = 'vagy';
$labels['yes'] = 'igen';
$labels['no'] = 'nem';
$labels['again'] = 'próbáld újra';

$labels['label'] = 'Név';
$labels['qrcode'] = 'QR kód';
$labels['showqrcode'] = 'QR kód megjelenítése';
$labels['qrcodeexplaintotp'] = 'Szkenneld be a QR kódot az autentikációs alkalmazásoddal';
$labels['qrcodeexplainhotp'] = 'Szkenneld be a QR kódot az autentikációs alkalmazásoddal';

$labels['yubikeyid'] = 'YubiKey azonosítód';
$labels['yubikeyidexplainyubikey'] = 'Nyomd meg a YubiKey-t, majd küldd el a generált kódot';

$labels["invalidauthenticatorresponse"] = "Érvénytelen autentikációs megerősítési válasz";
$labels["invaliddatainup"] = "Érvénytelen adat a felhasználói profilban.";
$labels["invalidsessiondata"] = "Érvénytelen munkamenet adat.";
$labels["invalidauthenticatordata"] = "Érvénytelen autentikációs adat";


$labels['factorforcedinfo'] = "Ahhoz, hogy folytathasd, be kell állítanod a 2FA-t, az alábbiak közül választva egy hitelesítési tényezőt.";
$labels['addfactor'] = 'Hitelesítési tényező hozzáadása';
$labels['testfactor'] = 'Tényező tesztelése';
$labels['verifycode'] = 'Kód ellenőrzése';
$labels['verifycodeexplaintotp'] = 'Miután beolvastad a QR kódot, add meg az autentikációs alkalmazás által generált 6-jegyű ellenőrzőkódot.';
$labels['verifycodeexplainhotp'] = 'Miután beolvastad a QR kódot, add meg az autentikációs alkalmazás által generált 6-jegyű ellenőrzőkódot.';

$labels['onlysinglebackupcodes'] = 'Egy időben csak egy halmaz helyreállítási kódod lehet';

$labels['loginexpired'] = 'A bejelentkezési kérés lejárt! Kérlek, próbáld újra.';
$labels['authremoveconfirm'] = 'Biztosan el akarod távolítani ezt a hitelesítési tényezőt a fiókodról?';
$labels['verifycodemissing'] = 'Kérlek, add meg a készülékedről származó ellenőrzőkódot';

$labels['factorsavesuccess'] = 'A hitelesítési tényező sikeresen elmentve';
$labels['factorremovesuccess'] = 'A hitelesítési tényező sikeresen eltávolítva';
$labels['factorsaveerror'] = 'A hitelesítési tényező beállításainak mentése sikertelen';
$labels['codeverificationpassed'] = 'A kódellenőrzés a(z) $method tényezőnél sikeresen megtörtént';
$labels['codeverificationfailed'] = 'A kódellenőrzés a(z) $method tényezőnél sikertelen';

$labels['highsecurityrequired'] = 'További ellenőrzés szükséges';
$labels['highsecuritydialog'] = 'A fiód biztonságának védelme érdekében – például a munkamenetlopás vagy mások általi beavatkozás megakadályozása érdekében – ellenőrizned kell a hitelesítő adataidat egy további hitelesítési tényező segítségével:';
$labels['enterhighsecurity'] = 'Megerősítés';

