<?php
$labels['machinetranslated'] = 'Machine Translated using Qwen 3 30B A3B Instruct 2507. In case of errors please open an issue at <a href="https://github.com/bennet0496/kolab_2fa_webauthn">bennet0496/kolab_2fa_webauthn</a>';

$labels['factor'] = 'Factor';
$labels['secret'] = 'Geheime sleutel';
$labels['created'] = 'Aangemaakt';
$labels['remove'] = 'Verwijderen';
$labels['continue'] = 'Doorgaan';

$labels['2faloginfailed'] = 'Verificatie van tweede factor mislukt';
$labels['choose_other'] = 'Kies een andere methode';

$labels['settingslist'] = 'Multi-factor authenticatie';
$labels['settingstitle'] = 'Authenticatiefactoren';

$labels['totp'] = 'Mobiele app (TOTP)';
$labels['hotp'] = 'Mobiele app (HOTP)';
$labels['yubikey'] = 'YubiKey';
$labels['webauthn'] = 'Beveiligings sleutel';
$labels['backupcodes'] = 'Back-upcodes';

$labels['or'] = 'of';
$labels['yes'] = 'ja';
$labels['no'] = 'nee';
$labels['again'] = 'probeer opnieuw';

$labels['label'] = 'Naam';
$labels['qrcode'] = 'QR-code';
$labels['showqrcode'] = 'Toon QR-code';
$labels['qrcodeexplaintotp'] = 'Scan de QR-code hieronder met uw authenticator-app';
$labels['qrcodeexplainhotp'] = 'Scan de QR-code hieronder met uw authenticator-app';

$labels['yubikeyid'] = 'Uw YubiKey-ID';
$labels['yubikeyidexplainyubikey'] = 'Druk één keer op uw YubiKey en stuur het gegenereerde code in';

$labels["invalidauthenticatorresponse"] = "Ongeldige authenticatorassertie-antwoord";
$labels["invaliddatainup"] = "Ongeldige gegevens in gebruikersprofiel.";
$labels["invalidsessiondata"] = "Ongeldige sessiegegevens.";
$labels["invalidauthenticatordata"] = "Ongeldige authenticatorgegevens";


$labels['factorforcedinfo'] = "U moet 2FA instellen om door te gaan, door hieronder een authenticatiefactor toe te voegen.";
$labels['addfactor'] = 'Voeg authenticatiefactor toe';
$labels['testfactor'] = 'Test deze factor';
$labels['verifycode'] = 'Code verifiëren';
$labels['verifycodeexplaintotp'] = 'Zodra u de QR-code hebt gescand, voert u de 6-cijferige verificatiecode in die is gegenereerd door de authenticator-app.';
$labels['verifycodeexplainhotp'] = 'Zodra u de QR-code hebt gescand, voert u de 6-cijferige verificatiecode in die is gegenereerd door de authenticator-app.';

$labels['onlysinglebackupcodes'] = 'U kunt op elk moment slechts één set back-upcodes hebben';

$labels['loginexpired'] = 'Inlogverzoek is verlopen! Probeer het opnieuw.';
$labels['authremoveconfirm'] = 'Wilt u deze authenticatiefactor echt verwijderen van uw account?';
$labels['verifycodemissing'] = 'Voer de verificatiecode van uw apparaat in';

$labels['factorsavesuccess'] = 'Authenticatiefactor succesvol opgeslagen';
$labels['factorremovesuccess'] = 'Authenticatiefactor succesvol verwijderd';
$labels['factorsaveerror'] = 'Fout bij opslaan van authenticatiefactorinstellingen';
$labels['codeverificationpassed'] = 'Codeverificatie voor $method geslaagd';
$labels['codeverificationfailed'] = 'Codeverificatie voor $method mislukt';

$labels['highsecurityrequired'] = 'Extra verificatie vereist';
$labels['highsecuritydialog'] = 'Om uw account te beschermen tegen veiligheidsbedreigingen, zoals sessiestealing of iemand die uw gegevens aanpast terwijl u weg bent, moet u uw referenties verifiëren met een extra authenticatiefactor:';
$labels['enterhighsecurity'] = 'Bevestig';

