<?php
$labels['machinetranslated'] = 'Machine Translated using Qwen 3 30B A3B Instruct 2507. In case of errors please open an issue at <a href="https://github.com/bennet0496/kolab_2fa_webauthn">bennet0496/kolab_2fa_webauthn</a>';

$labels['factor'] = 'Фактор';
$labels['secret'] = 'Секретный ключ';
$labels['created'] = 'Создано';
$labels['remove'] = 'Удалить';
$labels['continue'] = 'Продолжить';

$labels['2faloginfailed'] = 'Проверка второго фактора не удалась';
$labels['choose_other'] = 'Выбрать другой метод';

$labels['settingslist'] = 'Многофакторная аутентификация';
$labels['settingstitle'] = 'Факторы аутентификации';

$labels['totp'] = 'Мобильное приложение (TOTP)';
$labels['hotp'] = 'Мобильное приложение (HOTP)';
$labels['yubikey'] = 'YubiKey';
$labels['webauthn'] = 'Ключ безопасности';
$labels['backupcodes'] = 'Коды резервного копирования';

$labels['or'] = 'или';
$labels['yes'] = 'да';
$labels['no'] = 'нет';
$labels['again'] = 'попробовать еще раз';

$labels['label'] = 'Имя';
$labels['qrcode'] = 'QR-код';
$labels['showqrcode'] = 'Показать QR-код';
$labels['qrcodeexplaintotp'] = 'Отсканируйте QR-код ниже с помощью приложения-аутентификатора';
$labels['qrcodeexplainhotp'] = 'Отсканируйте QR-код ниже с помощью приложения-аутентификатора';

$labels['yubikeyid'] = 'Ваш идентификатор YubiKey';
$labels['yubikeyidexplainyubikey'] = 'Нажмите на ваш YubiKey один раз и отправьте сгенерированный код';

$labels["invalidauthenticatorresponse"] = "Недопустимый ответ аутентификатора";
$labels["invaliddatainup"] = "Недопустимые данные в профиле пользователя.";
$labels["invalidsessiondata"] = "Недопустимые данные сессии.";
$labels["invalidauthenticatordata"] = "Недопустимые данные аутентификатора";


$labels['factorforcedinfo'] = "Чтобы продолжить, необходимо настроить 2FA, добавив фактор аутентификации ниже.";
$labels['addfactor'] = 'Добавить фактор аутентификации';
$labels['testfactor'] = 'Проверить этот фактор';
$labels['verifycode'] = 'Подтвердить код';
$labels['verifycodeexplaintotp'] = 'После сканирования QR-кода введите 6-значный код подтверждения, сгенерированный приложением-аутентификатором.';
$labels['verifycodeexplainhotp'] = 'После сканирования QR-кода введите 6-значный код подтверждения, сгенерированный приложением-аутентификатором.';

$labels['onlysinglebackupcodes'] = 'Вы можете иметь только одну группу резервных кодов в любой момент времени';

$labels['loginexpired'] = 'Запрос на вход истек! Пожалуйста, попробуйте снова.';
$labels['authremoveconfirm'] = 'Вы действительно хотите удалить этот фактор аутентификации из своего аккаунта?';
$labels['verifycodemissing'] = 'Пожалуйста, введите код подтверждения со своего устройства';

$labels['factorsavesuccess'] = 'Фактор аутентификации успешно сохранен';
$labels['factorremovesuccess'] = 'Фактор аутентификации успешно удален';
$labels['factorsaveerror'] = 'Не удалось сохранить настройки фактора аутентификации';
$labels['codeverificationpassed'] = 'Проверка кода для $method пройдена';
$labels['codeverificationfailed'] = 'Проверка кода для $method не удалась';

$labels['highsecurityrequired'] = 'Требуется дополнительная проверка';
$labels['highsecuritydialog'] = 'Чтобы защитить ваш аккаунт от угроз безопасности, таких как кража сессии или попытки вмешательства в вашу информацию, когда вы отсутствуете, необходимо подтвердить свои учетные данные с помощью дополнительного фактора аутентификации:';
$labels['enterhighsecurity'] = 'Подтвердить';

