<?php
$labels['machinetranslated'] = 'Machine Translated using Qwen 3 30B A3B Instruct 2507. In case of errors please open an issue at <a href="https://github.com/bennet0496/kolab_2fa_webauthn">bennet0496/kolab_2fa_webauthn</a>';

$labels['factor'] = 'Faktör';
$labels['secret'] = 'Gizli Anahtar';
$labels['created'] = 'Oluşturuldu';
$labels['remove'] = 'Kaldır';
$labels['continue'] = 'Devam et';

$labels['2faloginfailed'] = 'İkinci faktör doğrulaması başarısız oldu';
$labels['choose_other'] = 'Diğer Yöntemi Seç';

$labels['settingslist'] = 'Çok Faktörlü Kimlik Doğrulama';
$labels['settingstitle'] = 'Kimlik Doğrulama Faktörleri';

$labels['totp'] = 'Mobil Uygulama (TOTP)';
$labels['hotp'] = 'Mobil Uygulama (HOTP)';
$labels['yubikey'] = 'YubiKey';
$labels['webauthn'] = 'Güvenlik Anahtarı';
$labels['backupcodes'] = 'Yedek Kodlar';

$labels['or'] = 'veya';
$labels['yes'] = 'evet';
$labels['no'] = 'hayır';
$labels['again'] = 'tekrar dene';

$labels['label'] = 'İsim';
$labels['qrcode'] = 'QR Kodu';
$labels['showqrcode'] = 'QR Kodunu Göster';
$labels['qrcodeexplaintotp'] = 'Aşağıdaki QR kodunu Kimlik Doğrulama Uygulamanızla tarayın';
$labels['qrcodeexplainhotp'] = 'Aşağıdaki QR kodunu Kimlik Doğrulama Uygulamanızla tarayın';

$labels['yubikeyid'] = 'YubiKey ID\'niz';
$labels['yubikeyidexplainyubikey'] = 'YubiKey\'inizi bir kez basıp oluşturulan kodu gönderin';

$labels["invalidauthenticatorresponse"] = "Geçersiz Kimlik Doğrulama Bildirimi";
$labels["invaliddatainup"] = "Kullanıcı Profilinde Geçersiz Veri.";
$labels["invalidsessiondata"] = "Geçersiz Oturum Verisi.";
$labels["invalidauthenticatordata"] = "Geçersiz Kimlik Doğrulama Verisi";


$labels['factorforcedinfo'] = "Devam etmek için 2FA ayarlamak zorundasınız, lütfen aşağıdaki kimlik doğrulama faktörünü ekleyin.";
$labels['addfactor'] = 'Kimlik Doğrulama Faktörü Ekle';
$labels['testfactor'] = 'Bu faktörü test et';
$labels['verifycode'] = 'Kodu Doğrula';
$labels['verifycodeexplaintotp'] = 'QR kodunu taradıktan sonra, kimlik doğrulama uygulaması tarafından oluşturulan 6 haneli doğrulama kodunu girin.';
$labels['verifycodeexplainhotp'] = 'QR kodunu taradıktan sonra, kimlik doğrulama uygulaması tarafından oluşturulan 6 haneli doğrulama kodunu girin.';

$labels['onlysinglebackupcodes'] = 'Herhangi bir anda yalnızca bir set yedek kodunuz olabilir';

$labels['loginexpired'] = 'Oturum açma isteği süresi doldu! Lütfen tekrar deneyin.';
$labels['authremoveconfirm'] = 'Bu kimlik doğrulama faktörünü hesabınızdan gerçekten kaldırmak istiyor musunuz?';
$labels['verifycodemissing'] = 'Lütfen cihazınızdan doğrulama kodunu girin';

$labels['factorsavesuccess'] = 'Kimlik doğrulama faktörü başarıyla kaydedildi';
$labels['factorremovesuccess'] = 'Kimlik doğrulama faktörü başarıyla kaldırıldı';
$labels['factorsaveerror'] = 'Kimlik doğrulama faktörü ayarları kaydedilemedi';
$labels['codeverificationpassed'] = '$method için kod doğrulaması başarılı oldu';
$labels['codeverificationfailed'] = '$method için kod doğrulaması başarısız oldu';

$labels['highsecurityrequired'] = 'Ek doğrulama gerekiyor';
$labels['highsecuritydialog'] = 'Hesabınızın güvenlik tehditlerinden (örneğin oturum çalınması veya uzakta olduğunuz sırada birinin işinizi bozması) korunması için, ek kimlik doğrulama faktörüyle kimlik bilgilerinizi doğrulamanız gerekir:';
$labels['enterhighsecurity'] = 'Doğrula';