<?php
$labels['machinetranslated'] = 'Machine Translated using Qwen 3 30B A3B Instruct 2507. In case of errors please open an issue at <a href="https://github.com/bennet0496/kolab_2fa_webauthn">bennet0496/kolab_2fa_webauthn</a>';

$labels['factor'] = '因素';
$labels['secret'] = '密钥';
$labels['created'] = '创建时间';
$labels['remove'] = '移除';
$labels['continue'] = '继续';

$labels['2faloginfailed'] = '二次验证失败';
$labels['choose_other'] = '选择其他方法';

$labels['settingslist'] = '多因素认证';
$labels['settingstitle'] = '认证因素';

$labels['totp'] = '手机应用 (TOTP)';
$labels['hotp'] = '手机应用 (HOTP)';
$labels['yubikey'] = 'YubiKey';
$labels['webauthn'] = '安全密钥';
$labels['backupcodes'] = '备用代码';

$labels['or'] = '或';
$labels['yes'] = '是';
$labels['no'] = '否';
$labels['again'] = '再试一次';

$labels['label'] = '名称';
$labels['qrcode'] = '二维码';
$labels['showqrcode'] = '显示二维码';
$labels['qrcodeexplaintotp'] = '使用您的认证应用扫描下方二维码';
$labels['qrcodeexplainhotp'] = '使用您的认证应用扫描下方二维码';

$labels['yubikeyid'] = '您的 YubiKey ID';
$labels['yubikeyidexplainyubikey'] = '按下您的 YubiKey 一次，并提交生成的代码';

$labels["invalidauthenticatorresponse"] = "无效的认证器断言响应";
$labels["invaliddatainup"] = "用户资料中数据无效。";
$labels["invalidsessiondata"] = "会话数据无效。";
$labels["invalidauthenticatordata"] = "认证器数据无效";


$labels['factorforcedinfo'] = "您需要设置双重验证才能继续，请在下方添加一个认证因素。";
$labels['addfactor'] = '添加认证因素';
$labels['testfactor'] = '测试此因素';
$labels['verifycode'] = '验证代码';
$labels['verifycodeexplaintotp'] = '扫描二维码后，请输入认证应用生成的6位验证代码。';
$labels['verifycodeexplainhotp'] = '扫描二维码后，请输入认证应用生成的6位验证代码。';

$labels['onlysinglebackupcodes'] = '您任何时候只能拥有一组备用代码';

$labels['loginexpired'] = '登录请求已过期！请重新尝试。';
$labels['authremoveconfirm'] = '您确定要从账户中移除此认证因素吗？';
$labels['verifycodemissing'] = '请填写来自您设备的验证代码';

$labels['factorsavesuccess'] = '成功保存认证因素';
$labels['factorremovesuccess'] = '成功移除认证因素';
$labels['factorsaveerror'] = '保存认证因素设置失败';
$labels['codeverificationpassed'] = '代码验证成功：$method';
$labels['codeverificationfailed'] = '代码验证失败：$method';

$labels['highsecurityrequired'] = '需要额外验证';
$labels['highsecuritydialog'] = '为保护您的账户免受安全威胁（如会话窃取或他人在您离开时篡改您的信息），您需要通过额外的认证因素确认您的凭证：';
$labels['enterhighsecurity'] = '确认';